import{a as p,S as A,N as C,A as S,P as k,i as d}from"./assets/vendor-BQjjM57f.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function s(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(r){if(r.ep)return;r.ep=!0;const n=s(r);fetch(r.href,n)}})();const g="https://sound-wave.b.goit.study/api";async function h(e=1,t=null,s=null,o=null){try{const n=g+"/artists",c={limit:8,page:e,name:t,sortName:s,genre:o};return(await p.get(n,{params:c})).data}catch(r){console.error("Error fetching artists:",r)}}async function B(e=1){const s=g+"/feedbacks",o={limit:10,page:e};try{return(await p.get(s,{params:o})).data}catch(r){console.error("Error fetching feedbacks:",r)}}const M=document.querySelector(".swiper-wrapper"),f=document.querySelector(".swiper-button-next"),m=document.querySelector(".swiper-button-prev"),a=document.querySelectorAll(".custom-pagination .dot");function q(e){const t=Math.round(e||0);let s="";for(let o=1;o<=5;o++){const r=o<=t?"#764191":"#D9D9D9";s+=`<span class="star" style="color: ${r};">★</span>`}return`<div class="feedback-rating">${s}</div>`}function P(e){return e.map(t=>`
        <li class="swiper-slide">
          ${q(t.rating)}
          <p class="slide-feedback">"${t.descr}"</p>
          <p class="feedback-author">${t.name}</p>
        </li>
      `).join("")}async function x(){try{const e=await B();if(e&&e.data&&e.data.length>0){const t=e.data.slice(0,10),s=P(t);M.insertAdjacentHTML("beforeend",s);const o=new A(".mySwiper",{modules:[C,S,k],slidesPerView:1,centeredSlides:!0,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{el:".swiper-pagination",dynamicBullets:!0,dynamicMainBullets:3},keyboard:{enabled:!0},on:{slideChange:function(){m.classList.toggle("swiper-button-disabled",this.isBeginning),f.classList.toggle("swiper-button-disabled",this.isEnd),a.forEach(r=>r.classList.remove("active")),this.activeIndex===0?a[0].classList.add("active"):this.activeIndex===9?a[2].classList.add("active"):a[1].classList.add("active")}},breakpoints:{0:{slidesPerView:1,loop:!1},768:{slidesPerView:1,loop:!1},1440:{slidesPerView:1,loop:!1}}});m.classList.add("swiper-button-disabled"),t.length<=1&&f.classList.add("swiper-button-disabled"),a.forEach(r=>{r.addEventListener("click",()=>{const n=r.dataset.index;n==="first"&&o.slideTo(0),n==="middle"&&o.slideTo(1),n==="last"&&o.slideTo(9)})}),a[0].classList.add("active")}}catch(e){console.log(e.message)}}x();const $=document.querySelector("[data-menu-open]"),I=document.querySelector("[data-menu-close]"),u=document.querySelector(".mob-menu");$.addEventListener("click",()=>{u.classList.add("is-open"),document.body.style.overflow="hidden"});I.addEventListener("click",()=>{u.classList.remove("is-open"),document.body.style.overflow=""});document.querySelector(".logo").addEventListener("click",function(){window.location.href="index.html"});const T=document.querySelector(".page-header");window.addEventListener("scroll",()=>{const e=window.scrollY,s=Math.max(0,1-e/250);T.style.setProperty("--gradient-opacity",s)});document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(t){t.preventDefault();const s=this.getAttribute("href").substring(1),o=document.getElementById(s);o&&o.scrollIntoView({behavior:"smooth",block:"start"})})});document.querySelectorAll(".mob-menu-nav a").forEach(e=>{e.addEventListener("click",()=>{u.classList.remove("is-open"),document.body.style.overflow=""})});const N=document.querySelector("#artist-cards");function O(e){const t=!e.genres||e.genres.length===0?"<li></li>":e.genres.map(s=>`<li class="genre-chip">${s}</li>`).join("");return`
        <li class="artist-card" data-artist-id="${e._id}">
            <img class="artist-photo" src="${e.strArtistThumb}" alt="artist photo">
            <ul class="artist-genre-list">
                ${t}
            </ul>
            <h4 class="artist-name">${e.strArtist}</h4>
            <p class="artist-info">${e.strBiographyEN}</p>
            <button class="artist-button learn-more-btn" data-artist-id="${e._id}">Learn More
                <svg class="artist-button-icon" width="24" height="24">
                    <use href="../img/about-us-img/about-us.svg#icon-icon"></use>
                </svg>
            </button>
        </li>
    `}function y(e,t=N){if(!Array.isArray(e)||!e.length)return;const s=e.map(o=>O(o)).join("");t.insertAdjacentHTML("beforeend",s)}function F(e){e.classList.remove("is-hidden")}function b(e){e.classList.add("is-hidden")}function w(e=document.querySelector(".preloader-box")){e&&e.classList.remove("is-hidden")}function v(e=document.querySelector(".preloader-box")){e&&e.classList.add("is-hidden")}const L=8;let l=1;const i={cardsContainer:document.querySelector("#artist-cards"),loadMoreBtn:document.querySelector(".btn-more")};async function R(){try{w();const e=await h(l);if(!e||!Array.isArray(e.artists))throw new Error("No artists found in the response");y(e.artists,i.cardsContainer),e.totalArtists&&l*L<e.totalArtists?F(i.loadMoreBtn):b(i.loadMoreBtn)}catch(e){console.error(e),d.error({title:"Error",message:"Не удалось загрузить артистов.",position:"topRight",timeout:3e3,titleColor:"#fff",backgroundColor:"#d63031",messageColor:"#fff"})}finally{v()}}async function E(e){e.target.blur(),l++,w();try{const t=await h(l);if(!t||!Array.isArray(t.artists))throw new Error("No artists found in the response");y(t.artists,i.cardsContainer);const s=i.cardsContainer.lastElementChild;await new Promise(r=>setTimeout(r,100));const o=s.getBoundingClientRect().height;window.scrollBy({top:o*1,behavior:"smooth"}),t.totalArtists&&l*L>=t.totalArtists&&(d.info({title:"",message:"You see all Artists.",position:"topRight",timeout:4e3,titleColor:"#fff",backgroundColor:"#764191",messageColor:"#fff"}),b(i.loadMoreBtn),i.loadMoreBtn.removeEventListener("click",E))}catch(t){console.error(t),d.error({title:"Error",message:"Houston we have a problem.",position:"topRight",timeout:3e3,titleColor:"#fff",backgroundColor:"#d63031",messageColor:"#fff"})}finally{v()}}function j(e){const t=e.target.closest(".learn-more-btn");!t||t.dataset.artistId}document.addEventListener("DOMContentLoaded",R);i.loadMoreBtn.addEventListener("click",E);i.cardsContainer.addEventListener("click",j);
//# sourceMappingURL=index.js.map
