import{a as L,i as l}from"./assets/vendor-BLO6kU33.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const b=document.querySelector("[data-menu-open]"),w=document.querySelector("[data-menu-close]"),d=document.querySelector(".mob-menu");b.addEventListener("click",()=>{d.classList.add("is-open"),document.body.style.overflow="hidden"});w.addEventListener("click",()=>{d.classList.remove("is-open"),document.body.style.overflow=""});document.querySelector(".logo").addEventListener("click",function(){window.location.href="index.html"});const v=document.querySelector(".page-header");window.addEventListener("scroll",()=>{const t=window.scrollY,s=Math.max(0,1-t/250);v.style.setProperty("--gradient-opacity",s)});const C=document.querySelector("#artist-cards");function A(t){const e=!t.genres||t.genres.length===0?"<li></li>":t.genres.map(s=>`<li class="genre-chip">${s}</li>`).join("");return`
        <li class="artist-card" data-artist-id="${t._id}">
            <img class="artist-photo" src="${t.strArtistThumb}" alt="artist photo">
            <ul class="artist-genre-list">
                ${e}
            </ul>
            <h4 class="artist-name">${t.strArtist}</h4>
            <p class="artist-info">${t.strBiographyEN}</p>
            <button class="artist-button learn-more-btn" data-artist-id="${t._id}">Learn More
                <svg class="artist-button-icon" width="24" height="24">
                    <use href="../img/about-us-img/about-us.svg#icon-icon"></use>
                </svg>
            </button>
        </li>
    `}function u(t,e=C){if(!Array.isArray(t)||!t.length)return;const s=t.map(i=>A(i)).join("");e.insertAdjacentHTML("beforeend",s)}function E(t){t.classList.remove("is-hidden")}function f(t){t.classList.add("is-hidden")}function m(t=document.querySelector(".preloader-box")){t&&t.classList.remove("is-hidden")}function h(t=document.querySelector(".preloader-box")){t&&t.classList.add("is-hidden")}const M="https://sound-wave.b.goit.study/api";async function g(t=1,e=null,s=null,i=null){try{const o=M+"/artists",a={limit:8,page:t,name:e,sortName:s,genre:i};return(await L.get(o,{params:a})).data}catch(r){console.error("Error fetching artists:",r)}}const p=8;let c=1;const n={cardsContainer:document.querySelector("#artist-cards"),loadMoreBtn:document.querySelector(".btn-more")};async function B(){try{m();const t=await g(c);if(!t||!Array.isArray(t.artists))throw new Error("No artists found in the response");u(t.artists,n.cardsContainer),t.totalArtists&&c*p<t.totalArtists?E(n.loadMoreBtn):f(n.loadMoreBtn)}catch(t){console.error(t),l.error({title:"Error",message:"Не удалось загрузить артистов.",position:"topRight",timeout:3e3,titleColor:"#fff",backgroundColor:"#d63031",messageColor:"#fff"})}finally{h()}}async function y(t){t.target.blur(),c++,m();try{const e=await g(c);if(!e||!Array.isArray(e.artists))throw new Error("No artists found in the response");u(e.artists,n.cardsContainer);const s=n.cardsContainer.lastElementChild;await new Promise(r=>setTimeout(r,100));const i=s.getBoundingClientRect().height;window.scrollBy({top:i*1,behavior:"smooth"}),e.totalArtists&&c*p>=e.totalArtists&&(l.info({title:"",message:"You see all Artists.",position:"topRight",timeout:4e3,titleColor:"#fff",backgroundColor:"#764191",messageColor:"#fff"}),f(n.loadMoreBtn),n.loadMoreBtn.removeEventListener("click",y))}catch(e){console.error(e),l.error({title:"Error",message:"Houston we have a problem.",position:"topRight",timeout:3e3,titleColor:"#fff",backgroundColor:"#d63031",messageColor:"#fff"})}finally{h()}}function q(t){const e=t.target.closest(".learn-more-btn");!e||e.dataset.artistId}document.addEventListener("DOMContentLoaded",B);n.loadMoreBtn.addEventListener("click",y);n.cardsContainer.addEventListener("click",q);
//# sourceMappingURL=index.js.map
