import{a as f,S as L,N as E,A,P as C,i as d}from"./assets/vendor-BQjjM57f.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();const m="https://sound-wave.b.goit.study/api";async function p(e=1,t=null,o=null,s=null){try{const n=m+"/artists",c={limit:8,page:e,name:t,sortName:o,genre:s};return(await f.get(n,{params:c})).data}catch(r){console.error("Error fetching artists:",r)}}async function S(e=1){const o=m+"/feedbacks",s={limit:10,page:e};try{return(await f.get(o,{params:s})).data}catch(r){console.error("Error fetching feedbacks:",r)}}const k=document.querySelector(".swiper-wrapper");document.querySelector(".swiper-button-next");document.querySelector(".swiper-button-prev");const a=document.querySelectorAll(".custom-pagination .dot");function M(e){const t=Math.round(e||0);let o="";for(let s=1;s<=5;s++){const r=s<=t?"#764191":"#D9D9D9";o+=`<span class="star" style="color: ${r};">★</span>`}return`<div class="feedback-rating">${o}</div>`}function B(e){return e.map(t=>`
        <li class="swiper-slide">
          ${M(t.rating)}
          <p class="slide-feedback">"${t.descr}"</p>
          <p class="feedback-author">${t.name}</p>
        </li>
      `).join("")}async function q(){try{const e=await S();if(e&&e.data&&e.data.length>0){const t=e.data.slice(0,10),o=B(t);k.insertAdjacentHTML("beforeend",o);const s=new L(".mySwiper",{modules:[E,A,C],slidesPerView:1,centeredSlides:!0,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{el:".swiper-pagination",dynamicBullets:!0,dynamicMainBullets:3},keyboard:{enabled:!0},on:{slideChange:function(){a.forEach(r=>r.classList.remove("active")),this.activeIndex===0?a[0].classList.add("active"):this.activeIndex===9?a[2].classList.add("active"):a[1].classList.add("active")}},breakpoints:{0:{slidesPerView:1,loop:!1},768:{slidesPerView:1,loop:!1},1440:{slidesPerView:1,loop:!1}}});a.forEach(r=>{r.addEventListener("click",()=>{const n=r.dataset.index;n==="first"&&s.slideTo(0),n==="middle"&&s.slideTo(1),n==="last"&&s.slideTo(9)})}),a[0].classList.add("active")}}catch(e){console.log(e.message)}}q();const P=document.querySelector("[data-menu-open]"),x=document.querySelector("[data-menu-close]"),u=document.querySelector(".mob-menu");P.addEventListener("click",()=>{u.classList.add("is-open"),document.body.style.overflow="hidden"});x.addEventListener("click",()=>{u.classList.remove("is-open"),document.body.style.overflow=""});document.querySelector(".logo").addEventListener("click",function(){window.location.href="index.html"});const $=document.querySelector(".page-header");window.addEventListener("scroll",()=>{const e=window.scrollY,o=Math.max(0,1-e/250);$.style.setProperty("--gradient-opacity",o)});document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(t){t.preventDefault();const o=this.getAttribute("href").substring(1),s=document.getElementById(o);s&&s.scrollIntoView({behavior:"smooth",block:"start"})})});document.querySelectorAll(".mob-menu-nav a").forEach(e=>{e.addEventListener("click",()=>{u.classList.remove("is-open"),document.body.style.overflow=""})});const I=document.querySelector("#artist-cards");function T(e){const t=!e.genres||e.genres.length===0?"<li></li>":e.genres.map(o=>`<li class="genre-chip">${o}</li>`).join("");return`
        <li class="artist-card" data-artist-id="${e._id}">
            <img class="artist-photo" src="${e.strArtistThumb}" alt="artist photo">
            <ul class="artist-genre-list">
                ${t}
            </ul>
            <h4 class="artist-name">${e.strArtist}</h4>
            <p class="artist-info">${e.strBiographyEN}</p>
            <button class="artist-button learn-more-btn" data-artist-id="${e._id}">Learn More
                <svg class="artist-button-icon" width="24" height="24">
                    <use href="../img/about-us-img/about-us.svg#icon-icon"></use>
                </svg>
            </button>
        </li>
    `}function g(e,t=I){if(!Array.isArray(e)||!e.length)return;const o=e.map(s=>T(s)).join("");t.insertAdjacentHTML("beforeend",o)}function N(e){e.classList.remove("is-hidden")}function h(e){e.classList.add("is-hidden")}function y(e=document.querySelector(".preloader-box")){e&&e.classList.remove("is-hidden")}function b(e=document.querySelector(".preloader-box")){e&&e.classList.add("is-hidden")}const w=8;let l=1;const i={cardsContainer:document.querySelector("#artist-cards"),loadMoreBtn:document.querySelector(".btn-more")};async function O(){try{y();const e=await p(l);if(!e||!Array.isArray(e.artists))throw new Error("No artists found in the response");g(e.artists,i.cardsContainer),e.totalArtists&&l*w<e.totalArtists?N(i.loadMoreBtn):h(i.loadMoreBtn)}catch(e){console.error(e),d.error({title:"Error",message:"Не удалось загрузить артистов.",position:"topRight",timeout:3e3,titleColor:"#fff",backgroundColor:"#d63031",messageColor:"#fff"})}finally{b()}}async function v(e){e.target.blur(),l++,y();try{const t=await p(l);if(!t||!Array.isArray(t.artists))throw new Error("No artists found in the response");g(t.artists,i.cardsContainer);const o=i.cardsContainer.lastElementChild;await new Promise(r=>setTimeout(r,100));const s=o.getBoundingClientRect().height;window.scrollBy({top:s*1,behavior:"smooth"}),t.totalArtists&&l*w>=t.totalArtists&&(d.info({title:"",message:"You see all Artists.",position:"topRight",timeout:4e3,titleColor:"#fff",backgroundColor:"#764191",messageColor:"#fff"}),h(i.loadMoreBtn),i.loadMoreBtn.removeEventListener("click",v))}catch(t){console.error(t),d.error({title:"Error",message:"Houston we have a problem.",position:"topRight",timeout:3e3,titleColor:"#fff",backgroundColor:"#d63031",messageColor:"#fff"})}finally{b()}}function F(e){const t=e.target.closest(".learn-more-btn");!t||t.dataset.artistId}document.addEventListener("DOMContentLoaded",O);i.loadMoreBtn.addEventListener("click",v);i.cardsContainer.addEventListener("click",F);
//# sourceMappingURL=index.js.map
